dist: xenial
language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8-dev"
    - "nightly"

sudo: false

matrix:
  fast_finish: true
  include:
    - os: osx
      language: generic
      python:

install: pip install tox-travis coveralls

before_install:
    - export TZ=America/Los_Angeles
    - date

script:
    - tox

matrix:
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"

notifications:
  irc:
    channels:
      - "irc.freenode.org#code-hell"
    on_success: change  # options: [always|never|change] default: always
    on_failure: never  # options: [always|never|change] default: always
    on_start: false     # default: false

